services:
  - type: web
    name: hectorquintana-stripe-api
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm run stripe:start
    envVars:
      - key: STRIPE_SERVER_PORT
        value: 4242
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: hectorquintana-web
    buildCommand: npm ci && npm run build
    publishPath: dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_STRIPE_API_URL
        sync: false
